name: dzshka

on:
  push:
    branches: ["main"]

jobs:
  proces:

    runs-on: ubuntu-latest

    steps:
      - name: rep_copy
        uses: actions/checkout@v1
      - name: py_install
        uses: actions/setup-python@v2
        with:
          python-version: 3.9
      - name: script
        run: |
          python test_dz.py
      - name: "telegram Nortifications"
        uses: "appleboy/telegram-action@master"
        with:
          to: -1001652215410
          token: 5655775691:AAH2jJKxQp6E5X7RGgTctlFIlpkXRNuVcxE
          args: good!
